### ISSUE TITLE
[FEATURE-REQUEST] Hostname should not need to be statically configured in the config

### ISSUE THREAD

**Issue by Nothing4You** [server-status-project/server-status#125]
**Is your feature request related to a problem? Please describe.**
When using different domains for the same page that are not necessarily both accessible to the user at the same time it would be useful to dynamically detect the hostname in use.

**Describe the solution you'd like**
It could be changed to use domain-relative URLs in most places and the config would only define the base path.
The only place that actually requires a full URL with domain and protocol is the account creation invitation email, which could be built e.g. from `$_SERVER["SERVER_PROTOCOL"]."://".$_SERVER["HTTP_HOST"]`.

**Describe alternatives you've considered**
\-

**Was this considered before?**
Not as far as I can tell.

**Additional context**
(Added by team) We are trying example scenarios.

**Comment by Nothing4You** [comment]
I was thinking about something along the lines of https://github.com/Nothing4You/server-status/commit/ba67453cd1a9ecd3f5a0f9b0b2c3d9f7793baee4

**Comment by yigitkeremoktay** [comment]
Hi @Nothing4You we have now received your request. We'll consider and respond to you soon.

**Comment by yigitkeremoktay** [comment]
Just like in WordPress you can simply get around this inside the config file like it is in WordPress

**Comment by Pryx** [comment]
My main issue with this is that I don't see the use-case here... Why would anyone host the same content on two different domains? Maybe I'm just missing something? :slightly_smiling_face:

**Comment by Nothing4You** [comment]
I guess I just forgot that PHP allows variables in constant assignments, thanks.

To explain my usecase:
I'm running multiple instances, a public one with more information and a private one with less information.
Depending on whether you're in the internal or external network you get to see the other instance.
To allow management of both they also have a dedicated hostname.
