### ISSUE TITLE
[FEATURE-REQUEST] Add an issue bot

### ISSUE THREAD

**Issue by yigitkeremoktay** [server-status-project/server-status#127]
**Is your feature request related to a problem? Please describe.**
Yes. There are so many inactive issues

**Describe the solution you'd like**
We should add an issue bot.

**Describe alternatives you've considered**
Not any so far.

**Was this considered before?**
Nope.

**Comment by Pryx** [comment]
This seems worth considering :slightly_smiling_face: We would definitely have to create a new label "pinned" or something that would not close issues that should be considered in future development :wink:

**Comment by yigitkeremoktay** [comment]
Hey @Pryx @server-status-project/server-status-core The issue bot does not seem to be affecting the old issues.

**Comment by Pryx** [comment]
They are pinned, so it should not :slightly_smiling_face:  Those issues should not be closed just because we didn't fix them within a month :slightly_smiling_face:
