### ISSUE TITLE
[FEATURE-REQUEST]

### ISSUE THREAD

**Issue by mikolajstolarski94** [server-status-project/server-status#133]
I've created an initial version of dockerized environment for your project.
There are few steps, that you need to figure out, so I hope someone will save the time.
If you're interested, you colud adopt it in your project :)

https://github.com/mikolajstolarski94/server-status-docker

**Comment by yigitkeremoktay** [comment]
We made our development environment public here https://github.com/server-status-project/server-status-docker.

Thanks for your suggestion.
