### ISSUE TITLE
Manually set admin user/password

### ISSUE THREAD

**Issue by btsherid** [server-status-project/server-status#138]
Hi,

I'm trying to do an automated install so I need to use config.php. I got it up and running by doing that, but I'm getting this: 

Warning: Use of undefined constant admin - assumed 'admin' (this will throw an Error in a future version of PHP) in /opt/app-root/src/template.php on line 59

This also means I can't access the admin page. So is there a way I can manually set the admin username/password in the code? Trying to use the automated installer didn't work for how I'm trying to set it up.

Thank You,
Brendan Sheridan

**Comment by thnilsen** [comment]
The user/password is stored in the db. Why not create a standard installation manually, then make a backup of the database and the config.php file and use that as a base for your automated install?

**Comment by btsherid** [comment]
Thanks. I was able to use the web installer to create the user/password in the db and then use it later in my manual install.
