### ISSUE TITLE
Visibility Not Working

### ISSUE THREAD

**Issue by btsherid** [server-status-project/server-status#139]
Hi,

I've got an instance of this up and working and I created some Services and Service Groups. The main page shows no difference between a Service Group with visibility Expanded and visibility Collapsed. Any ideas?

Thanks,
Brendan Sheridan

**Comment by thnilsen** [comment]
This behavior is as expected, as the visibility setting is not yet implemented on the front page. 

- Thomas

**Comment by btsherid** [comment]
OK thanks. Do you have a timeframe for implementation?

-Brendan

**Comment by Pryx** [comment]
Implemented in e5a0db1; Will have to test all the changes and hopefully beta should be released soon-ish :slightly_smiling_face:
