### ISSUE TITLE
Admin credentials for demo do not work

### ISSUE THREAD

**Issue by FWDekker** [server-status-project/server-status#149]
Hiya! I tried to log in on the demo at https://demo.status.sajdl.com/admin with email address `sysadmin@example.com` and password `Ss123456` as specified in the README, but doing so gives me the error `Wrong email or password`. I suppose the credentials are wrong or maybe outdated. Has the password been changed?

**Comment by Pryx** [comment]
Thanks for the report, seems like the automatic database reset wasn't working properly. It should be now fixed and you should be able to access the demo :slightly_smiling_face:

**Comment by FWDekker** [comment]
Works perfectly now, thanks!
