### ISSUE TITLE
Not going well V1.1

### ISSUE THREAD

**Issue by 13LuckyBack** [server-status-project/server-status#150]
Well i am trying to get it good but i get this isntead:
![Screenshot_3](https://user-images.githubusercontent.com/50382721/116331195-87012480-a7cf-11eb-8b27-799c815e9311.png)
And when i try to log in the admin panel i get this:
![Screenshot_4](https://user-images.githubusercontent.com/50382721/116331198-8799bb00-a7cf-11eb-8422-e02b561fd03f.png)
 
How can i fix this?

**Comment by thnilsen** [comment]
Check your web server logs to see if they can  give you any clues as to what's failing. 
Did the install routine work OK?

**Comment by 13LuckyBack** [comment]
Install routine wokred ok.
And i checked the logs and see nothing wrong in my eyes (Not that good with websites tho.)

**Comment by jhuesser** [comment]
Error 500 means server side error, so the PHP error should be logged in an error.log or something on your webserver. Are you self hosting or using a Webhoster?

**Comment by 13LuckyBack** [comment]
Web hoster.
Vimexx
Direct Admin

**Comment by jhuesser** [comment]
You can find the error log here: https://www.vimexx.eu/help/foutlog-directadmin <https://www.vimexx.eu/help/foutlog-directadmin>

What does it say?

**Comment by 13LuckyBack** [comment]
[Wed Apr 28 04:37:46.422337 2021] [lsapi:error] [pid 97643:tid 140124146841344] [client 86.91.251.61:56553] [host luckydevelopment.online] Backend fatal error: PHP Fatal error:  Uncaught Error: Call to undefined method mysqli_stmt::get_result() in /home/u52845p89930/domains/luckydevelopment.online/public_html/classes/constellation.php:129\nStack trace:\n#0 /home/u52845p89930/domains/luckydevelopment.online/public_html/classes/constellation.php(30): Constellation->get_incidents(true, 0, 6, 1619577466)\n#1 /home/u52845p89930/domains/luckydevelopment.online/public_html/index.php(42): Constellation->render_incidents(true, 0)\n#2 {main}\n  thrown in /home/u52845p89930/domains/luckydevelopment.online/public_html/classes/constellation.php on line 129\n
[Wed Apr 28 04:37:49.855600 2021] [lsapi:error] [pid 97643:tid 140123794347776] [client 86.91.251.61:56553] [host luckydevelopment.online] Backend fatal error: PHP Fatal error:  Uncaught Error: Call to undefined method mysqli_stmt::get_result() in /home/u52845p89930/domains/luckydevelopment.online/public_html/classes/constellation.php:129\nStack trace:\n#0 /home/u52845p89930/domains/luckydevelopment.online/public_html/classes/constellation.php(30): Constellation->get_incidents(true, 0, 6, 1619577469)\n#1 /home/u52845p89930/domains/luckydevelopment.online/public_html/index.php(42): Constellation->render_incidents(true, 0)\n#2 {main}\n  thrown in /home/u52845p89930/domains/luckydevelopment.online/public_html/classes/constellation.php on line 129\n
[Wed Apr 28 04:38:32.044646 2021] [lsapi:error] [pid 97643:tid 140124188804864] [client 86.91.251.61:56553] [host luckydevelopment.online] Backend fatal error: PHP Fatal error:  Uncaught Error: Call to undefined method mysqli_stmt::get_result() in /home/u52845p89930/domains/luckydevelopment.online/public_html/classes/user.php:229\nStack trace:\n#0 /home/u52845p89930/domains/luckydevelopment.online/public_html/admin/index.php(28): User::login()\n#1 {main}\n  thrown in /home/u52845p89930/domains/luckydevelopment.online/public_html/classes/user.php on line 229\n, referer: https://luckydevelopment.online/admin/
[Wed Apr 28 04:38:37.551947 2021] [lsapi:error] [pid 97643:tid 140123743991552] [client 86.91.251.61:56553] [host luckydevelopment.online] Backend fatal error: PHP Fatal error:  Uncaught Error: Call to undefined method mysqli_stmt::get_result() in /home/u52845p89930/domains/luckydevelopment.online/public_html/classes/user.php:229\nStack trace:\n#0 /home/u52845p89930/domains/luckydevelopment.online/public_html/admin/index.php(28): User::login()\n#1 {main}\n  thrown in /home/u52845p89930/domains/luckydevelopment.online/public_html/classes/user.php on line 229\n, referer: https://luckydevelopment.online/admin/
[Wed Apr 28 17:04:52.582349 2021] [lsapi:error] [pid 58683:tid 140095986231040] [client 86.91.251.61:52440] [host luckydevelopment.online] Backend fatal error: PHP Fatal error:  Uncaught Error: Call to undefined method mysqli_stmt::get_result() in /home/u52845p89930/domains/luckydevelopment.online/public_html/classes/user.php:229\nStack trace:\n#0 /home/u52845p89930/domains/luckydevelopment.online/public_html/admin/index.php(28): User::login()\n#1 {main}\n  thrown in /home/u52845p89930/domains/luckydevelopment.online/public_html/classes/user.php on line 229\n, referer: https://luckydevelopment.online/admin/
[Wed Apr 28 17:04:55.788705 2021] [lsapi:error] [pid 61141:tid 140095734449920] [client 86.91.251.61:52440] [host luckydevelopment.online] Backend fatal error: PHP Fatal error:  Uncaught Error: Call to undefined method mysqli_stmt::get_result() in /home/u52845p89930/domains/luckydevelopment.online/public_html/classes/constellation.php:129\nStack trace:\n#0 /home/u52845p89930/domains/luckydevelopment.online/public_html/classes/constellation.php(30): Constellation->get_incidents(true, 0, 6, 1619622295)\n#1 /home/u52845p89930/domains/luckydevelopment.online/public_html/index.php(42): Constellation->render_incidents(true, 0)\n#2 {main}\n  thrown in /home/u52845p89930/domains/luckydevelopment.online/public_html/classes/constellation.php on line 129\n, referer: https://luckydevelopment.online/admin/

**Comment by thnilsen** [comment]
Sounds like your web host is using the mysqli PHP module, while you will need the mysqlnd PHP module for server-status to work. Not sure if it is available as an option in the control panel of your webhoster to switch, but if not check with their support.

**Comment by 13LuckyBack** [comment]
It is turned on and still.

https://prnt.sc/127kqm5

**Comment by thnilsen** [comment]
Turn off mysqli

**Comment by 13LuckyBack** [comment]
Then i still get the 500.

**Comment by thnilsen** [comment]
Could it be that the changes on PHP modules is only applied after a certain amount of time? I know one.com hosting has up to 1 hour delay for when the reload such changes?
If the log file shows the same _"Call to undefined method mysqli_stmt::get_result() in ...."_ error I suspect its because mysqlnd isn't active yet. 

Another thing to check is that the database has actually been created and has data in the users table.

You could also create a test file on the web server with the following content:
`<?php 

phpinfo();`

Load up this with your browser and see if the mysqli module is still listed - as it should not be.

**Comment by 13LuckyBack** [comment]
Well i turned that one off and waited a time but now i can't enter the whole website with code 500

**Comment by thnilsen** [comment]
What does the error logs show now?

Did you try the test file? Check it and make sure mysqlnd is listed.

**Comment by 13LuckyBack** [comment]
[Wed Apr 28 04:37:46.422337 2021] [lsapi:error] [pid 97643:tid 140124146841344] [client MYIP] [host luckydevelopment.online] Backend fatal error: PHP Fatal error:  Uncaught Error: Call to undefined method mysqli_stmt::get_result() in /home/u52845p89930/domains/luckydevelopment.online/public_html/classes/constellation.php:129\nStack trace:\n#0 /home/u52845p89930/domains/luckydevelopment.online/public_html/classes/constellation.php(30): Constellation->get_incidents(true, 0, 6, 1619577466)\n#1 /home/u52845p89930/domains/luckydevelopment.online/public_html/index.php(42): Constellation->render_incidents(true, 0)\n#2 {main}\n  thrown in /home/u52845p89930/domains/luckydevelopment.online/public_html/classes/constellation.php on line 129\n
[Wed Apr 28 04:37:49.855600 2021] [lsapi:error] [pid 97643:tid 140123794347776] [client MYIP] [host luckydevelopment.online] Backend fatal error: PHP Fatal error:  Uncaught Error: Call to undefined method mysqli_stmt::get_result() in /home/u52845p89930/domains/luckydevelopment.online/public_html/classes/constellation.php:129\nStack trace:\n#0 /home/u52845p89930/domains/luckydevelopment.online/public_html/classes/constellation.php(30): Constellation->get_incidents(true, 0, 6, 1619577469)\n#1 /home/u52845p89930/domains/luckydevelopment.online/public_html/index.php(42): Constellation->render_incidents(true, 0)\n#2 {main}\n  thrown in /home/u52845p89930/domains/luckydevelopment.online/public_html/classes/constellation.php on line 129\n
[Wed Apr 28 04:38:32.044646 2021] [lsapi:error] [pid 97643:tid 140124188804864] [client MYIP] [host luckydevelopment.online] Backend fatal error: PHP Fatal error:  Uncaught Error: Call to undefined method mysqli_stmt::get_result() in /home/u52845p89930/domains/luckydevelopment.online/public_html/classes/user.php:229\nStack trace:\n#0 /home/u52845p89930/domains/luckydevelopment.online/public_html/admin/index.php(28): User::login()\n#1 {main}\n  thrown in /home/u52845p89930/domains/luckydevelopment.online/public_html/classes/user.php on line 229\n, referer: https://luckydevelopment.online/admin/
[Wed Apr 28 04:38:37.551947 2021] [lsapi:error] [pid 97643:tid 140123743991552] [client MYIP] [host luckydevelopment.online] Backend fatal error: PHP Fatal error:  Uncaught Error: Call to undefined method mysqli_stmt::get_result() in /home/u52845p89930/domains/luckydevelopment.online/public_html/classes/user.php:229\nStack trace:\n#0 /home/u52845p89930/domains/luckydevelopment.online/public_html/admin/index.php(28): User::login()\n#1 {main}\n  thrown in /home/u52845p89930/domains/luckydevelopment.online/public_html/classes/user.php on line 229\n, referer: https://luckydevelopment.online/admin/
[Wed Apr 28 17:04:52.582349 2021] [lsapi:error] [pid 58683:tid 140095986231040] [client MYIP] [host luckydevelopment.online] Backend fatal error: PHP Fatal error:  Uncaught Error: Call to undefined method mysqli_stmt::get_result() in /home/u52845p89930/domains/luckydevelopment.online/public_html/classes/user.php:229\nStack trace:\n#0 /home/u52845p89930/domains/luckydevelopment.online/public_html/admin/index.php(28): User::login()\n#1 {main}\n  thrown in /home/u52845p89930/domains/luckydevelopment.online/public_html/classes/user.php on line 229\n, referer: https://luckydevelopment.online/admin/
[Wed Apr 28 17:04:55.788705 2021] [lsapi:error] [pid 61141:tid 140095734449920] [client MYIP] [host luckydevelopment.online] Backend fatal error: PHP Fatal error:  Uncaught Error: Call to undefined method mysqli_stmt::get_result() in /home/u52845p89930/domains/luckydevelopment.online/public_html/classes/constellation.php:129\nStack trace:\n#0 /home/u52845p89930/domains/luckydevelopment.online/public_html/classes/constellation.php(30): Constellation->get_incidents(true, 0, 6, 1619622295)\n#1 /home/u52845p89930/domains/luckydevelopment.online/public_html/index.php(42): Constellation->render_incidents(true, 0)\n#2 {main}\n  thrown in /home/u52845p89930/domains/luckydevelopment.online/public_html/classes/constellation.php on line 129\n, referer: https://luckydevelopment.online/admin/

**Comment by 13LuckyBack** [comment]
When i turn off mysqli i can't acces the site and when its on i can.

**Comment by 13LuckyBack** [comment]
But only on admin side its not working for some reason.

**Comment by 13LuckyBack** [comment]
Yes i fixed the problem i tryed to reset all PHP Extensions and now its working.
