### ISSUE TITLE
Expired HTTPS cert on the demo site

### ISSUE THREAD

**Issue by jc-dgit** [server-status-project/server-status#154]
Looks like the HTTPS cert has expired on the demo site:

![Screen Shot 2021-07-16 at 11 05 40 pm](https://user-images.githubusercontent.com/82353280/125952566-a74acbd0-4abc-4c54-989f-f13bafafb2c5.png)

**Comment by jhuesser** [comment]
@Pryx Needs to fix it, as it's running on his host.

**Comment by Pryx** [comment]
Fixed, thanks for the report @jc-dgit  🙂
