### ISSUE TITLE
Fatal error on demo page [Error]

### ISSUE THREAD

**Issue by Cale-Torino** [server-status-project/server-status#174]
Hi, Today I wanted to take a look at the demo site: https://demo.status.sajdl.com/admin and I noticed that it has a Fatal error in PHP when I login with the provided credentials....

Credentials used:
```
email: sysadmin@example.com
password: Ss123456
```

Image of error:

<img width="961" alt="Screenshot 2024-01-08 132452" src="https://github.com/server-status-project/server-status/assets/52330180/2f1e5422-d11a-4275-a7ea-c4e8e4de11d8">

Just wanted to make a note of it.

Thanks for the Server status project.

**Comment by adaniieel** [comment]
Hello @Cale-Torino, thank you for your report.

[https://server-status.oppersitios.com/](https://server-status.oppersitios.com/)
email: sysadmin@example.com
password: Ss123456

I have created a new demo. If you, @Pryx @jhuesser , would like, I can submit a pull request to update the readme, or anyone can make the change in the readme.

**Comment by Steffen-MLR** [comment]
@Cale-Torino thanks for reporting. We will update the example server.
@adaniieel please check the pull-request.
