### ISSUE TITLE
Add ability to customize config from web

### ISSUE THREAD

**Issue by Pryx** [server-status-project/server-status#23]
It might be useful to move some config stuff to database so it is editable. Also this way more configuration can be added without the hassle of parsing the config file and writing it again. Some basic stuff will have to remain there, but it should really be the basics like database connection. 

In addition to current settings it would be nice to add setting for number of shown incidents, now it's hardcoded to 5. 

This would also mean the need to revisit settings gui - suggestions welcome.

**Comment by yigitkeremoktay** [comment]
We finally added this on beta! You may now try it!
