### ISSUE TITLE
Help text for services

### ISSUE THREAD

**Issue by jhuesser** [server-status-project/server-status#51]
How about a help text for services, to explain the user what is included. Something like https://status.coinbase.com/ has. Maybe we can "steal" some code from https://themes.gohugo.io/cstate/ ?

**Comment by Pryx** [comment]
That's a great idea, thanks :slightly_smiling_face: should be fairly straightforward to add, you're welcome to pick it up if you want, otherwise I will

**Comment by jhuesser** [comment]
I can try it. I guess I need JS and I'm not really good at it. But I'll see what I can do.

**Comment by Pryx** [comment]
Server status is made with Bootstrap so it should be possible to use their tooltips. https://getbootstrap.com/docs/3.3/javascript/

**Comment by jhuesser** [comment]
Ahh good input, thank you.

**Comment by yigitkeremoktay** [comment]
Please refer to https://github.com/server-status-project/server-status/issues/90. It is not yet fully implemented so you can add your own code. 😉

**Comment by yigitkeremoktay** [comment]
This feature was added tı the new V2 Beta.
Thanks!
