### ISSUE TITLE
Set end time for major outage and minor outage

### ISSUE THREAD

**Issue by mattfleaydaly** [server-status-project/server-status#52]
This could be a good feature?
Would like to create an end time similar to maintenance for each outage type.

**Comment by mattfleaydaly** [comment]
@Pryx Sure!
In the sense that if you've got a Major outage, but you know that it will be restored at the latest by a certain time, you can set that as the end time for the alert incase you don't get around to removing it.
I know in the circumstance that i'm using this script, this feature would be very very well used. 
http://widgets.whitmoregroup.com.au/routes.php for context.

**Comment by yigitkeremoktay** [comment]
@mattfleaydaly this feature is now replaced by planned maintenance. you can find it in master. You may now close this issue
