### ISSUE TITLE
Options for de-branding

### ISSUE THREAD

**Issue by SigmaScorpii** [server-status-project/server-status#58]
This is something I would like to have. Might be a duplication.

I would like to change the copyright text and the link to the GitHub source. 
This would be useful inside business context, which is where I use this status panel.
You could also make this some sort of a pay-to-get option to protect your copyright rights.

**Comment by Pryx** [comment]
I can see how this could be useful and I am willing to compromise. Would an attribution page be acceptable? I do not want to de-brand completely so it is possible to find the original project :slightly_smiling_face:

**Comment by SigmaScorpii** [comment]
Such a page would be acceptable.
But I don't think it would handy to make this a complete in coded page.

None of my team would take the time to compromise your rights and remove the contents of that pre-coded page, but I know there will be others out there who would change the contents of that page.
Would it be an option to make a system in the code which would give an error page when that page is removed or when it is changed?
You could for example make that contribution page somewhere else and make it display on the page you send to people when they download the source.
Then, whenever some smart ass would remove, or change it, their status page won't work anymore till they replace it.

**Comment by yigitkeremoktay** [comment]
https://github.com/Pryx/server-status/pull/114

**Comment by yigitkeremoktay** [comment]
Please close this issue as this feature was added. Thanks!
