### ISSUE TITLE
When Try to Login

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [server-status-project/server-status#59]
19-Sep-2018 16:13:12 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method mysqli_stmt::get_result() in /home/q2z6b02onlmp/public_html/status/classes/user.php:229
Stack trace:
#0 /home/q2z6b02onlmp/public_html/status/admin/index.php(28): User::login()
#1 {main}
  thrown in /home/q2z6b02onlmp/public_html/status/classes/user.php on line 229

**Comment by Pryx** [comment]
Do you have [mysqlnd](http://php.net/manual/en/book.mysqlnd.php) installed & enabled?

**Comment by ParveenBhadooOfficial** [comment]
It is a shared hosting at Godaddy. How to find mysqlnd is there or not?

**Comment by Pryx** [comment]
Try to enable nd_mysqli in php extensions and disable mysqli in Godaddy control panel. This is what I found on the internet and supposedly works (I don't have experience with Godaddy hosting, sorry)

**Comment by yigitkeremoktay** [comment]
This issue was inactive for too long closing.
