### ISSUE TITLE
Service grouping & ordering

### ISSUE THREAD

**Issue by Pryx** [server-status-project/server-status#7]
It should be possible to group and order services - users with more services could use that.

**Comment by SigmaScorpii** [comment]
Would this include some sort of a category group overview as well?
Par example: Category one gets the "minor outage label" if some services get an "major outage" or "minor outage".
And if everything goes to something different then operational it get "major outage".

**Comment by Pryx** [comment]
@SigmaScorpii it should be something like https://metastatuspage.com/ has, but design-wise I'm not set on how it will look like (yet).

**Comment by petrk94** [comment]
@Pryx I like this idea 👍

**Comment by yigitkeremoktay** [comment]
Feature added.
