### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by mobbdeep** [server-status-project/server-status#81]
Hello,

After uploading the content to my shared hosting server and visit the website, I'm greeted with the index page with PHP errors, not the installation wizard. I head over to the domain.com/install.php and complete the required fields and press "Install!", I just get redirected back to the index page. I then view phpmyadmin and notice nothing was imported into the database therefore  when I try logging into the /admin/ panel, I get thrown PHP errors. I even tried manually editing the config file because the index page originally throws PHP errors but still no luck.

Is there something I'm doing wrong?

**Comment by Pryx** [comment]
Hi, sorry for the late reply. Can you please paste the errors here? Thanks.

**Comment by mobbdeep** [comment]
Same issue as this guy https://github.com/Pryx/server-status/issues/59#issue-361826600.

I tried your solution but it didn't work. I have mysqlnd & nd_mysql installed and enabled with mysqli disabled, still no luck. Could the problem be with the PHP version? I tried on PHP 7.2.

**Comment by Pryx** [comment]
Resolved by #101

**Comment by yigitkeremoktay** [comment]
@mobbdeep can you try it from the beta here https://github.com/yigitkeremoktay/server-status or the latest stable master from https://github.com/pryx/server-status.

Make sure to delete all the database tables and files inside the installation dir. If the issue persists then please create a new issue at our official beta repository here https://github.com/yigitkeremoktay/server-status/issues so we can fix them in a future build as this repo only get stable updates. Thank You!

**Comment by yigitkeremoktay** [comment]
@mobbdeep We were able to recreate the issue on our end and we confirmed it was fixed. You are welcome to reopen this issue if it still persists.
