### ISSUE TITLE
What will happen when MySQL Server is down?

### ISSUE THREAD

**Issue by aligoren** [server-status-project/server-status#82]
I have an idea but how it would be, I don't know.

For example, the "server-status" is using "db.example.com" for database connections.

If the database doesn't work, the team member will not see statuses.

I think when SQL server doesn't work, this script also should return "SQL Server Status" or something like that.

The UI structure should be the same.

This is my question. I also have an idea.

For example, we also have "customerdb.example.com" for customer databases. This server is different than our main server. Even if our main DB server work, this may not be work.

For these kinds of statuses, users should have the ability to add "related services".

![diagram](https://user-images.githubusercontent.com/4205423/57176865-16d09a00-6e66-11e9-9114-a0cbfe05b943.png)

According to this diagram, if "customerdb.example.com" down, any web sites will not work.

So, if the user adds "customerdb.example.com" as a system and adds related systems with "customerdb" maybe work to show database connection lost statuses automatically for all websites which connected to "customerdb.example.com".

Example with Diagram.

![diagram2](https://user-images.githubusercontent.com/4205423/57177027-7b8cf400-6e68-11e9-92e5-c2828515fa61.png)

**Comment by yigitkeremoktay** [comment]
Closing this as it needs rethinking. You can reopen the issue if you have a fix for it. Thanks for your interest!
